### ISSUE TITLE
Resizing issues

### ISSUE THREAD

**Issue by strambc** [WU-BIMAC/4DNMicroscopyMetadataToolReact#93] opened 2020-06-23 17:35 UTC
**CORRECT RESIZING**
THE PROPORTION OF THE BOUNDING BOX WITH RESPECT TO THE ICON DOES NOT CHANGE
![image](https://user-images.githubusercontent.com/4050585/85436014-5bc9fb00-b556-11ea-81dc-20b54179f82b.png)

**Comment by strambc** [comment] 2020-06-23 17:36
**WRONG RESIZING**
THE PROPORTION OF THE BOUNDING BOX WITH RESPECT TO THE ICON CHANGES WITH SIZE
![image](https://user-images.githubusercontent.com/4050585/85436149-90d64d80-b556-11ea-99f4-34741b4e2ca7.png)

**Comment by strambc** [comment] 2020-06-23 17:41
THIS SAME ISSUE APPLIES TO:

- LightSourceCoupling _ Light Guide
- Em-Filter
- Objective Turret Focus
- Stage and Sample Holder

**Comment by Akramhar** [comment] 2020-07-13 23:07
This should be fixed for LightSourceCoupling, TurretFocus, IntensityCalibrationTool.
For what concern Excitation and Emission Filter I'm unable to reproduce similar behavior, the one I'm aware so far is currently related to the snap in place.
Stage and SampleHolder I'm unable to reproduce and I'm not aware of any related issue.
Could you please describe the issue more in detail?

**Closed** 2020-08-19 20:46 UTC
Labels: High, bug
