### ISSUE TITLE
Disproportionate bounding boxes

### ISSUE THREAD

**Issue by strambc** [WU-BIMAC/4DNMicroscopyMetadataToolReact#90] opened 2020-06-23 03:01 UTC
The dimension of the bounding box is too large and disproportionate (square) instead of following the size of the icon.

**Em- and Ex-Filter**
![image](https://user-images.githubusercontent.com/4050585/85356145-3c8e8780-b4dc-11ea-8791-0a969f15775a.png)

**Relay Lens and CouplingLens**
![image](https://user-images.githubusercontent.com/4050585/85434303-d47b8800-b553-11ea-835e-b8a04496b62c.png)

Is this something that has to be fixed by Alex or Shannon?

**Comment by strambc** [comment] 2020-06-23 17:19
**Intensity Calibration Tool**
![image](https://user-images.githubusercontent.com/4050585/85434500-245a4f00-b554-11ea-980d-aa479398a919.png)

**Comment by strambc** [comment] 2020-06-23 17:21
**AutoFocus**
![image](https://user-images.githubusercontent.com/4050585/85434687-6be0db00-b554-11ea-969d-34e203d943f6.png)

**Comment by strambc** [comment] 2020-06-23 17:23
**FocusingObjectiveTurret**
![image](https://user-images.githubusercontent.com/4050585/85434953-c9752780-b554-11ea-98b4-ba640b359c04.png)

**Comment by strambc** [comment] 2020-06-23 17:24
**Microscopy Table**
![image](https://user-images.githubusercontent.com/4050585/85435005-d8f47080-b554-11ea-8e34-6307325eeb49.png)

**Comment by strambc** [comment] 2020-06-23 17:27
**Optovar**
![image](https://user-images.githubusercontent.com/4050585/85435356-54562200-b555-11ea-84fb-df8b86f9e30c.png)

**Comment by strambc** [comment] 2020-06-23 17:29
**Stage and Sample Holder**
![image](https://user-images.githubusercontent.com/4050585/85435546-98e1bd80-b555-11ea-9805-7810d8e276bc.png)

**Comment by strambc** [comment] 2020-06-23 17:32
**Additional Optics + Mirror**
![image](https://user-images.githubusercontent.com/4050585/85435816-0a217080-b556-11ea-8d7e-d49560bd0242.png)

**Comment by Akramhar** [comment] 2020-07-13 23:18
IntensityCalibrationTool, LightSourceCoupling and ObjectiveTurretFocus had issues with the pre-set dimensions and have been fixed in 0.26.
For what concern the other element I have been unable to reproduce the error of having elements with the "squared" bounding box. Could you please tell me more about how you obtained this issue?
For what concern the additional optics / mirror I'm unable to see what the problem related bounding box would be.

**Comment by strambc** [comment] 2020-08-19 21:09
-- PROBLEM SOLVED WITH ALL STAGE ISSUE AND WITH CALIBRATION AND AUTOFOCUS
-- PROBLEM PARTIALLY PERSISTS WITH ALL OTHER ELEMENTS

PARTICULARLY NOTICEABLE WITH MICROSCOPE TABLE

**Comment by Akramhar** [comment] 2020-08-26 01:39
may be solved in 0.28

**Comment by strambc** [comment] 2020-08-26 09:52
-- PROBLEM SOLVED WITH TABLE, OPTOVAR, FOCUSING TURRET
-- PROBLEM PERSISTS WITH EX-FILTER, EM-FILTER, COUPLING LENS, RELAY LENS

**Comment by Akramhar** [comment] 2020-08-26 20:03
should be fixed in 0.28.2-a1

**Comment by strambc** [comment] 2020-08-26 23:36
-- PROBLEM FIXED WITH EM-FILTER
-- PROBLEM WITH EX-FILTER, COUPLING AND RELAY LENS PERSISTS

**Comment by strambc** [comment] 2020-08-26 23:42
ZOOMED IN

![image](https://user-images.githubusercontent.com/4050585/91367360-3070c000-e7d4-11ea-809d-1ea58cd0bffb.png)

ZOOMED OUT

![image](https://user-images.githubusercontent.com/4050585/91367408-4aaa9e00-e7d4-11ea-97c2-22b211a023b8.png)

**Comment by strambc** [comment] 2020-08-26 23:43
ALSO WEIRD THAT COUPLING AND RELAY ICONS HAVE DIFFERENT SIZES!

**Comment by Akramhar** [comment] 2020-08-27 00:51
thats how they are done by shannon
should be fixed in 0.28.3-a1

**Closed** 2020-12-28 05:51 UTC
Labels: GUI Change, High, bug
