### ISSUE TITLE
Any entry that is yes/no requires you to have the checkbox marked

### ISSUE THREAD

**Issue by paulamonterollopis** [WU-BIMAC/4DNMicroscopyMetadataToolReact#111] opened 2020-11-23 21:18 UTC
It seems in any entry that has a checkbox to check only if the entry is true (e. g tunable laser), the software treats it as not answered and required. Perhaps 2 checkboxes should be available? 

I think it may be a bug

**Comment by strambc** [comment] 2020-11-23 21:21
Dear Paula
I think this is a known issue.
Can you please try to check and un-check it and see if it now accepts it?

**Comment by paulamonterollopis** [comment] 2020-11-23 21:23
Yes, it now accepts it no problem.

Thank you.

Paula


Paula  Montero Llopis, PhD

MicRoN Director


77 Avenue Louis Pasteur

NRB1032

Office 617 432 0177

Cell 203 927 1468


micron.hms.harvard.edu


________________________________

**Comment by strambc** [comment] 2020-11-23 21:24
Great so this is a known issue we will fix in an upcoming release. The way it is is really ANNOYING and it has been noticed before.

**Comment by strambc** [comment] 2020-11-23 21:25
This is related to #105

**Comment by strambc** [comment] 2020-11-23 21:26
I am going to close this issue as it a duplicate of issue #105

**Closed by strambc** 2020-11-23 21:26 UTC
Labels: bug, duplicate

**Comment by paulamonterollopis** [comment] 2020-11-23 21:27
Oh, I am sorry! I think this is sort of what was happening with Joel and the environmental chamber 🙂


Paula  Montero Llopis, PhD

MicRoN Director


77 Avenue Louis Pasteur

NRB1032

Office 617 432 0177

Cell 203 927 1468


micron.hms.harvard.edu


________________________________

**Comment by strambc** [comment] 2020-11-23 21:34
No problem at all. Thank you for pointing it out!!!!
